name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ staging ]
    tags:
      - '*'

jobs:
  # Build job. Builds app for Windows with Pyinstaller
  build-windows:
    name: Build for Windows
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build for Windows with PyInstaller
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: reinforcement.spec


    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/windows/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: test_app
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}